### PR TITLE
Week 8 Assignment

### PR DESCRIPTION
**Pull request by Tatiwuli**

### CODE REVIEW

**Review by fee3fitri — COMMENTED** [review]
List of Work Experience (`ul` / `li`): You have used `<p>` tags inside the `<ul>` element, which is not semantically correct. Each item should be wrapped in `<li>` tags instead of `<p>` tags to maintain the correct list structure.

**Comment by Tatiwuli** [comment]
Hii Fifi! Thank you for the review. So , it will be like this: 
`   <ul>
      <li>- Data Analyst in StarBem</li>
      <li>- A smartwatch caffeine tracker at CalHacks</li>
      <li>
        - A educational platform that guide professors to implement innovative
        teaching
      </li>
      <li>- Programmed a robot to compete in First Robotics Competition (FRC)</li>
    </ul>`

**Comment by Tatiwuli** [comment]
> Hii Fifi! Thank you for the review. So , it will be like this: ` <ul> <li>- Data Analyst in StarBem</li> <li>- A smartwatch caffeine tracker at CalHacks</li> <li> - A educational platform that guide professors to implement innovative teaching </li> <li>- Programmed a robot to compete in First Robotics Competition (FRC)</li> </ul>`

@fee3fitri

**Comment by fee3fitri** [comment]
Yes! That works well!

**Pull request merged**
